### PR TITLE
Adding ClustalW2-2.1-foss-2016.09.eb

### PR DESCRIPTION
**Pull request by Pavithra-Gopal**

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@Pavithra-Gopal please rebuild clustalw2 with foss-2016.03 instead of 2016.09.

**Comment by Pavithra-Gopal** [comment]
Created rpm package ClustalW2-2.1-foss-2016.03-eb_3.3.1-2.x86_64.rpm and pushed the same to artifactory.

**Comment by Pavithra-Gopal** [comment]
@shahzebsiddiqui Please review the updated eb file (ClustalW2-2.1-foss-2016.03.eb)

**Comment by Pavithra-Gopal** [comment]
@shahzebsiddiqui I have deleted ClustalW2-2.1-foss-2016.09.eb file and the change is updated on github.

**Pull request merged**
